### ISSUE TITLE
a trouble in scaling app

### ISSUE THREAD

**Issue by CoolSpring8** [tengyifei/openshift-cartridge-nginx-hhvm#20]
Hello,
This may not have to do with this cartridge,but I'd like to thank you if you help me.Yesterday I used this cartridge to create an scalable application and installed WordPress on it. It ran well,but when I tried refreshing the page very quickly today,the local-gear seemed to go down(503,and then 504).
I checked haproxy-status and it seemed like to make another gea up.However,when I visited my site again,the page become the original "Welcome to OpenShift".
I tried restarting the application but it didn't work.Is that means the file and data can't be shared even between the two gears of an application?Or do I need to do anything extra to use an scalable app?(I noticed when I first visited the website,it set a cookie like "Set-Cookie:GEAR=local-1234567890f9337d81012345; path=/".I guess it can ensure the visitor visit a certain gear,but when the local gear goes down,it doesn't seem to help.)
Thanks!

**Comment by CoolSpring8** [comment]
Surprisingly,when I fininshed typing the words above,I found my site showed the page of WordPress again.But I'm still worried that the trouble may appear next time.

**Comment by tengyifei** [comment]
If you SSHed into the cartridge and pulled down a copy of WordPress from the internet, that is not the correct way to install WordPress :wink: You should copy WordPress into `www`folder of your own code repository, which will be automatically initialized for you after `rhc app create`. Then commit and push. The new version will start serving immediately.

Having said that, running WordPress on a PaaS framework differs somewhat from hosting it on a VPS. Writing to local file system is discouraged since changes are not propagated across gears.

**Comment by CoolSpring8** [comment]
Oh,thanks for telling me that.I'll try it.:)
